management:
  endpoints:
    web:
      exposure:
        include: '*'
autotrade:
  delta: ${AUTOTRADE_DELTA_VALUE}
  orderLimitValue: ${AUTOTRADE_ORDER_LIMIT_VALUE}
  spreadSize: ${AUTOTRADE_SPREAD_SIZE}
  quantityOfStrategies: ${AUTOTRADE_QUANTITY_OF_STRATEGIES}
kafka:
  names:
    topic:
      streams:
        optionPositions: ibkr_option_positions
        aggregatePositions: ibkr_positions_aggregate
        aggregateOptionMarketData: ibkr_options_market_aggregate
        optionChainData: ibkr_option_chain
      singlePnL: ibkr_single_pnl
      openOrders: ibkr_open_order
      historicalData: ibkr_historical
      orderData: ibkr_order
      accountPnL: ibkr_account_pnl
      contractData: ibkr_contract
      errorMessage: ibkr_error_message
      standardMarketData: ibkr_standard_market_data
      optionMarketData: ibkr_option_market_data
      accountSummary: ibkr_account_summary
      positions: ibkr_positions
  consumer:
    group:
      id: market_data_group
    rest:
      group:
        id: rest_response_group
    auto:
      group:
        id: auto_trade_group
#  bootstrap-servers: 192.168.127.215:9092
#  bootstrap-servers:   10.97.227.135:9092 moved to spring.kafka.bootstrap-servers because it is still used
logging:
  file:
    path: ../logs
app:
  constants:
    positions:
      call:
        id: '-20'
    account:
      summary:
        id: '-40'
    open:
      orders:
        id: '-30'
    time:
      millis: '000'
  ibkr:
    spx:
      ticker:
        id: 3214
    connectionId: '1'
    #7496 for live 7467 for paper
    tradingPort: 7497
    isReaderStarted: 'false'
    accountSummary:
      tags:
        BuyingPower: BuyingPower
        NetLiquidation: NetLiquidation
        AccruedCash: AccruedCash
    dateTimeFormat: yyyyMMdd-HH:mm:ss
    dateFormat: yyyyMMdd
    nextValidOrderId: '1'
    pnl:
      accountId: '1000'
    generic:
      ticks: '100'
spring:
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  jpa:
    defer-datasource-initialization: 'true'
server:
  address: 0.0.0.0
---
spring:
  config:
    activate:
      on-profile: staging
  kafka:
    bootstrap-servers: 10.97.227.135:9092
app:
  ibkr:
    tradingPort: 8888



---
spring:
  config:
    activate:
      on-profile: production
  kafka:
    bootstrap-servers: 10.97.227.135:9092
app:
  ibkr:
    tradingPort: 7496


