apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app
  labels:
    app: trading-app
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-app
  template:
    metadata:
      labels:
        app: trading-app
    spec:
      containers:
        - name: ibkr
          image: ghcr.io/extrange/ibkr # latest, stable, 10.21, 10.21.1p etc
          command: [ "sh", "-c", "ulimit -n 10000" ]
          securityContext:
            privileged: true
          ports:
            - containerPort: 6080
              name: no-vnc
            - containerPort: 8888
              name: api
          env:
            - name: USERNAME
              value:
            - name: PASSWORD
              value:
              # TWOFA_TIMEOUT_ACTION: restart
            - name: GATEWAY_OR_TWS
              value: "tws"
              # Variables prefixed with IBC_ override IBCAlpha`s config.ini:
            - name: IBC_TradingMode
              value: "paper"
            - name: IBC_ReadOnlyApi
              value: "no"
        - name: trading-app
          image: docker.io/segoy/trading-app
          ports:
            - containerPort: 8080
