apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app
  labels:
    app: trading-app
  namespace: trading
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-app
  template:
    metadata:
      labels:
        app: trading-app
    spec:
      containers:
        - name: ibkr
          image: ghcr.io/extrange/ibkr # latest, stable, 10.21, 10.21.1p etc
          ports:
            - containerPort: 6080
              name: noVNC
            - containerPort: 8888
              name: API
          ulimits:
            nofile: 10000 # See FAQ
          environment:
            USERNAME:  ${USERNAME}
            PASSWORD: ${PASSWORD}
              # TWOFA_TIMEOUT_ACTION: restart
            GATEWAY_OR_TWS: tws
              #
              # Variables prefixed with IBC_ override IBCAlpha`s config.ini:
            IBC_TradingMode: paper
            IBC_ReadOnlyApi: no
        - name: trading-app
          image: segoy/trading-app
          ports:
            - "8080:8080"
